# This file was generated by GoReleaser. DO NOT EDIT.
cask "daptin-cli" do
  version "0.8.4"

  on_macos do
    on_intel do
      sha256 "1ea0cc5af0e06bb541c0f073708e088a37082b118c9a01ff3611a19a348b4b31"
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d47c69275c90d73617e97ee63547967c62b4a965b10a5d8a1b2ab6e95decbaa5"
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82b75a06723bcc186420219f53b13dcf4741ddafa8600a1b5d6748a63b7da730"
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3b6b2e165529cd8b63e84cdb30ffd96e2a71adf4c453f1ec8cbc88c054d980c"
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "daptin-cli"
  desc "CLI client for Daptin API server"
  homepage "https://github.com/daptin/daptin-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daptin-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/daptin-cli"]
  end

  # No zap stanza required

end
