# This file was generated by GoReleaser. DO NOT EDIT.
cask "daptin-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "b32591f938914d6646df4f5effb623a06beca12131343887b1b8f7b27aa88951"
    end
    on_arm do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "9ced0ef815c66ab8c2bc1bd4fef3c16eb0b8fa1005642bba52307783e1efb62f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_linux_amd64.tar.gz"
      sha256 "b5d5c0f7d4eab5e4ad8d978e1150d452c2b0f186542285fc357196c7c9da3dcc"
    end
    on_arm do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_linux_arm64.tar.gz"
      sha256 "6de85f580abbb47e70966bd576634330a66322eeca7aaa537a85597ecd727456"
    end
  end

  name "daptin-cli"
  desc "CLI client for Daptin API server"
  homepage "https://github.com/daptin/daptin-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daptin-cli"

  # No zap stanza required

end
