# This file was generated by GoReleaser. DO NOT EDIT.
cask "daptin-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "240946d755f4b95d2f56c3e1e0bc82d54f0c1f17843b4126db8c28113eb0ccca"
    end
    on_arm do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "fafe0db02e23f70f98343d8b19bd71019b9dac94129a9654e62769072707cef8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_linux_amd64.tar.gz"
      sha256 "d0f7d82301b89af9e2024c15555f14bc15c0f80d6bbe19f50847f42759de4c07"
    end
    on_arm do
      url "https://github.com/daptin/daptin-cli/releases/download/v#{version}/daptin-cli_#{version}_linux_arm64.tar.gz"
      sha256 "7844562ebd4fc0553d9b8293e1c1a57d01f171f831da34f4d7f59a2f10461b28"
    end
  end

  name "daptin-cli"
  desc "CLI client for Daptin API server"
  homepage "https://github.com/daptin/daptin-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daptin-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/daptin-cli"]
  end

  # No zap stanza required

end
